version: '3.4'

services:
  db:
    container_name: "db"
    image: postgres:12.2-alpine
    ports:
      - '5431:5431'
    environment:
      - POSTGRES_USER=ApiBotTeleGrUser
      - POSTGRES_PASSWORD=ApiBotPS2007
      - POSTGRES_DB=ApiBotTeleGrUser
    networks:
      - deploy-guide-dev
    volumes:
      - database_postgres:/var/lib/postgresql/data
  bottelegrammsearchphone: 
    container_name: "bottelegrammsearchphone"
    image: ${DOCKER_REGISTRY-}bottelegrammsearchphone
    build:
      context: .
      dockerfile: BotTelegrammSearchPhone/Dockerfile
    ports:
      - "80:80"
    networks:
      - deploy-guide-dev
    depends_on:
      - db  

volumes:
  database_postgres:

networks:
  deploy-guide-dev:
    driver: bridge